// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: robo.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category *string `protobuf:"bytes,1,opt,name=category,proto3,oneof" json:"category,omitempty"`
}

func (x *Filter) Reset() {
	*x = Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_robo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_robo_proto_rawDescGZIP(), []int{0}
}

func (x *Filter) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

type Robo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model            string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	SerialNumber     string `protobuf:"bytes,2,opt,name=serialNumber,proto3" json:"serialNumber,omitempty"`
	ManufacturedDate string `protobuf:"bytes,3,opt,name=manufacturedDate,proto3" json:"manufacturedDate,omitempty"`
	Category         string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *Robo) Reset() {
	*x = Robo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Robo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Robo) ProtoMessage() {}

func (x *Robo) ProtoReflect() protoreflect.Message {
	mi := &file_robo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Robo.ProtoReflect.Descriptor instead.
func (*Robo) Descriptor() ([]byte, []int) {
	return file_robo_proto_rawDescGZIP(), []int{1}
}

func (x *Robo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Robo) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *Robo) GetManufacturedDate() string {
	if x != nil {
		return x.ManufacturedDate
	}
	return ""
}

func (x *Robo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type RoboList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoboList []*Robo `protobuf:"bytes,1,rep,name=roboList,proto3" json:"roboList,omitempty"`
}

func (x *RoboList) Reset() {
	*x = RoboList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoboList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoboList) ProtoMessage() {}

func (x *RoboList) ProtoReflect() protoreflect.Message {
	mi := &file_robo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoboList.ProtoReflect.Descriptor instead.
func (*RoboList) Descriptor() ([]byte, []int) {
	return file_robo_proto_rawDescGZIP(), []int{2}
}

func (x *RoboList) GetRoboList() []*Robo {
	if x != nil {
		return x.RoboList
	}
	return nil
}

var File_robo_proto protoreflect.FileDescriptor

var file_robo_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x6f, 0x62, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x06,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x22, 0x88, 0x01, 0x0a, 0x04, 0x72, 0x6f, 0x62, 0x6f, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x10, 0x6d, 0x61, 0x6e, 0x75, 0x66,
	0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x64, 0x44,
	0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22,
	0x2d, 0x0a, 0x08, 0x72, 0x6f, 0x62, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x08, 0x72,
	0x6f, 0x62, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e,
	0x72, 0x6f, 0x62, 0x6f, 0x52, 0x08, 0x72, 0x6f, 0x62, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x32, 0x35,
	0x0a, 0x0e, 0x52, 0x6f, 0x62, 0x6f, 0x41, 0x70, 0x6f, 0x63, 0x61, 0x6c, 0x79, 0x70, 0x73, 0x65,
	0x12, 0x23, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x62, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x07, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x1a, 0x09, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_robo_proto_rawDescOnce sync.Once
	file_robo_proto_rawDescData = file_robo_proto_rawDesc
)

func file_robo_proto_rawDescGZIP() []byte {
	file_robo_proto_rawDescOnce.Do(func() {
		file_robo_proto_rawDescData = protoimpl.X.CompressGZIP(file_robo_proto_rawDescData)
	})
	return file_robo_proto_rawDescData
}

var file_robo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_robo_proto_goTypes = []interface{}{
	(*Filter)(nil),   // 0: filter
	(*Robo)(nil),     // 1: robo
	(*RoboList)(nil), // 2: roboList
}
var file_robo_proto_depIdxs = []int32{
	1, // 0: roboList.roboList:type_name -> robo
	0, // 1: RoboApocalypse.GetRoboList:input_type -> filter
	2, // 2: RoboApocalypse.GetRoboList:output_type -> roboList
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_robo_proto_init() }
func file_robo_proto_init() {
	if File_robo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_robo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Robo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoboList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_robo_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_robo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_robo_proto_goTypes,
		DependencyIndexes: file_robo_proto_depIdxs,
		MessageInfos:      file_robo_proto_msgTypes,
	}.Build()
	File_robo_proto = out.File
	file_robo_proto_rawDesc = nil
	file_robo_proto_goTypes = nil
	file_robo_proto_depIdxs = nil
}
